//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cccc.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class KetQua
    {
        [Required]
        public int MaNV { get; set; }
        [Required]
        public string TenSp { get; set; }
        [Required]
        public Nullable<decimal> DonGia { get; set; }
        [Required][Range(1,50)]
        public Nullable<int> SoLuong { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
    }
}
